apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: ghcr.io/scholzj/kafka-consumer:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: BOOTSTRAP_SERVERS
            value: test-cluster-kafka-bootstrap.default.svc:9092
          - name: TOPIC
            value: myTopicAbcd
          - name: GROUP_ID
            value: my-kafka-consumer

