apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: myTopicAbcd
  labels:
    strimzi.io/cluster: test-cluster
spec:
  partitions: 5
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 8640000
      segment.bytes: 1073741824
